# Generated by Django 2.2.3 on 2019-10-17 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InputImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comparison_set_name', models.CharField(max_length=100)),
                ('input_image', models.ImageField(blank=True, max_length=254, null=True, upload_to='your_path')),
                ('standard_image', models.ImageField(blank=True, max_length=254, null=True, upload_to='your_path')),
            ],
        ),
        migrations.CreateModel(
            name='OutputImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output_image', models.ImageField(blank=True, max_length=254, null=True, upload_to='your_path')),
                ('input_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.InputImages')),
            ],
        ),
    ]
